### ISSUE TITLE
[Transfer]: Module Icinga

### ISSUE THREAD

**Issue by lbetz** [puppetlabs/forge_issues#21] opened 2024-05-17 16:07 UTC
### Deprecated module

https://forge.puppet.com/modules/icinga/icinga

### Replacement module

https://forge.puppet.com/modules/voxpupuli/icinga

### What authority do you have for making this request?

The repository has already been transferred

**Comment by binford2k** [comment] 2024-05-20 16:09
duplicate of #20

**Closed as completed by binford2k** 2024-05-20 16:09 UTC
Labels: triaged, administrative
